---
- name: Install PostgreSQL server
  apt:
    name: postgresql
    state: present

- name: Install psycopg2 package
  apt:
    name: python3-psycopg2
    state: present

- name: Configure PostgreSQL database
  becom: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    state: present

- name: Create PostgreSQL user
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    encrypted: yes
  