- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Clone application repository
  git:
    repo: https://github.com/Practical-DevOps/app-for-devops.git
    dest: /var/www/app
    clone: yes
    update: yes
  notify: Restart Apache
  

